### ISSUE TITLE
Unable to get table reference or create table. Aborting write operation.

### ISSUE THREAD

**Issue by Mikkelcv** [Azure/azure-functions-host#10995]
Previous function runtime: 4.1037.1.23605
Current function runtime: 4.1038.300.25164

After the function runtime version has been updated to 4.1038 then our function app periodicaly every 10 minutes reports the exception:

_"Unable to get table reference or create table. Aborting write operation."_

Message:
```
This request is not authorized to perform this operation using this permission.
Time:2025-04-11T11:38:55.5555894Z
Status: 403 (Forbidden)
ErrorCode: AuthorizationPermissionMismatch
```

The execption originates in:
`{"assembly":"Microsoft.Azure.WebJobs.Script.WebHost, Version=4.1038.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository+<FlushLogs>d__30.MoveNext","level":34,"line":195,"fileName":"/_/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventTableStorageRepository.cs"}`

Granting the function app: "StorageTableDataContributor" RBAC role on the storage enables the function app to create an empty table in the storage.

Why is it now a requirement that this empty table must be created? 
How do we disable this so we can have the old functionallity back?

It is NOT an option to grant this RBAC role to all function apps, we do not need this and wont grant access that is not required otherwise.

The guide: 
https://learn.microsoft.com/en-us/azure/azure-functions/storage-considerations?tabs=azure-cli

Does not explain that the access is required. Is it something that is on its way?

**Comment by asos-chanhkiethuynh** [comment]
We have been experiencing the same issue as well out of no where, since 26/04/2025.

**Comment by scrocquesel-ml150** [comment]
Neither is https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob&pivots=programming-language-csharp#connecting-to-host-storage-with-an-identity updated.
This is related to modification done for https://github.com/Azure/azure-functions-host/issues/9569

**Comment by scrocquesel-ml150** [comment]
The role "Storage Table Data Contributor" on the storage account is enough.

**Comment by rob-thijssen** [comment]
I totally agree on all statements made by @Mikkelcv. Especially on this one:
```It is NOT an option to grant this RBAC role to all function apps, we do not need this and wont grant access that is not required otherwise.```

We're also experiencing this issue since april 11th, and our logs are already polluted with these messages for multiple subscriptions.
As a work-around we could add this statement: ```"Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository": "None"``` to host.json in the logging/loglevel section. But for obvious reasons this is not the desired solution. 
So could this please be fixed in a decent manner asap?

**Comment by WingTai** [comment]
We have also been experiencing this issue since around March 26th, with an increase in these errors since April 11th, even though we haven't deployed any new versions of the affected function apps in long time.

Any acknowledgement and fix from MSFT? Preferably would not like to apply the suggested workarounds.

**Comment by arjavgarg** [comment]
Yes, we also started seeing this issue on 3/26/2025, 9:25:43.665 AM (UTC)

**Comment by czeslav87** [comment]
+1

Multiple function apps, using Managed Identity access to storage with Storage Blob permissions only, started to throw this on 26th March 2025.

**Comment by LavanyaMullapudi2328** [comment]
Role assignment is not helping out. Still seeing the error even after assigning the "Storage Table Data Contributor " Role to the function app

**Comment by jviau** [comment]
This is a diagnostic feature running in the background. These failures are not impactful to the health of the app. There is a PR up to improve these logs.

For the time being you can add a log filter for `Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository` to host.json and filter out logs.

You can also disable this feature via an app setting: `AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging`

`AzureWebJobsFeatureFlags` is a comma separated list of values, so if you have other values append this with a comma separator.

https://learn.microsoft.com/azure/azure-functions/functions-app-settings#azurewebjobsfeatureflags

**Comment by SRE-Agent** [comment]
Thank you for reporting this issue. This behavior after runtime updates appears aligned with changes affecting table storage operations and RBAC role assignments, especially for diagnostic events. A related issue [#10970](https://github.com/Azure/azure-functions-host/issues/10970) is already tracking this concern, and it captures similar effects of inadequate permissions for the required roles, causing silent failures or misconfigurations. We recommend marking this issue as a duplicate of it.

Please review the suggested workarounds to disable diagnostic logging if unnecessary for your application:
1. Modify app settings: `AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging`.
2. Use host.json log filtering for `Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository`.

Let us know if you require further assistance or clarification.

**Comment by nzthiago** [comment]
@jviau if this exception is landing on customers' App Insights are we unnecessarily inflating their app insights (cost implications)?

**Comment by jviau** [comment]
@nzthiago the workarounds I provided will prevent it from going to app insights. The linked PR by @cjaliaga (#10996) will also greatly reduce the volume of telemetry emitted here. The diagnostic events feature will self-disable in this scenario (no permissions)

**Comment by nzthiago** [comment]
Aha - thank you, it's that linked PR I missed so that customers don't need any workaround.

**Comment by thenecroscope** [comment]
> This is a diagnostic feature running in the background. These failures are not impactful to the health of the app. There is a PR up to improve these logs.
> 
> For the time being you can add a log filter for `Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository` to host.json and filter out logs.
> 
> You can also disable this feature via an app setting: `AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging`
> 
> `AzureWebJobsFeatureFlags` is a comma separated list of values, so if you have other values append this with a comma separator.
> 
> https://learn.microsoft.com/azure/azure-functions/functions-app-settings#azurewebjobsfeatureflags


This almost works for us. One question please
Can we combine both of these, for example;

AzureWebJobsFeatureFlags=DisableDiagnosticEventTableStorageRepository

I would prefer to handle the filtering at the Environment variable level if possible as we have so many function apps to update.

Many thanks,

**Comment by thenecroscope** [comment]
> > This is a diagnostic feature running in the background. These failures are not impactful to the health of the app. There is a PR up to improve these logs.
> > For the time being you can add a log filter for `Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository` to host.json and filter out logs.
> > You can also disable this feature via an app setting: `AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging`
> > `AzureWebJobsFeatureFlags` is a comma separated list of values, so if you have other values append this with a comma separator.
> > https://learn.microsoft.com/azure/azure-functions/functions-app-settings#azurewebjobsfeatureflags
> 
> This almost works for us. One question please Can we combine both of these, for example;
> 
> AzureWebJobsFeatureFlags=DisableDiagnosticEventTableStorageRepository
> 
> I would prefer to handle the filtering at the Environment variable level if possible as we have so many function apps to update.
> 
> Many thanks,

Answered my own question:
AzureFunctionsJobHost__logging__logLevel__Azure.Data.Tables = None

This appears to work 👍

**Comment by seilorjunior** [comment]
I am also seeing this issue with my customer, we gave the role in the storage, but we are still having the exceptions.

**Comment by thenecroscope** [comment]
I tried several environment setting / variables but no luck so far:

AzureFunctionsJobHost__logging__logLevel__Azure.Data.Tables = None
AzureFunctionsJobHost__logging__logLevel__Microsoft.Azure.WebJobs.Extensions.Tables = None
Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository = None


I think this approach may have worked, but it goes over the 100 character variable limit, so that failed also.
AzureFunctionsJobHost__logging__logLevel__Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.DiagnosticEventTableStorageRepository = None

**Comment by thenecroscope** [comment]
I tried to rollback to the previous Image using:

FUNCTIONS_EXTENSION_VERSION = 4.1037.1 (plus a few different combinations)
This appears not work on an EP1 Linux plan running dotnet-isolated 8.0

Weirdly when I set the version to 1.37.1, it downloads image 4.1037.1, not sure why this is|

I cant work out the correct way to pin to a specific image.

**Comment by Qaizer** [comment]
@jviau 
Will this AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging have any other implications?

**Comment by thenecroscope** [comment]
> [@jviau](https://github.com/jviau) Will this AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging have any other implications?

For us this is not really a viable option unfortunately, as this will disable all logging and ideally we only want to disable Table logs for example

**Comment by jviau** [comment]
`AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging` will only impact table logs. Logs to application insights, open telemetry, and azure monitor will not be affected.

**Comment by scrocquesel-ml150** [comment]
Could we have some documentation on this diagnostic feature ? I have functions using classic connectionString with those table logs. Didn't pay attention to them until now. Is this an old feature ? What are the Microsoft recommandation, should it be disabled by default ?

**Comment by Fatalo83** [comment]
In my case is was a different issue. To connect to the storage account for my functions I use Access Keys so I didn't think it was RBAC releated. 

I am using a private endpoint to integrate the storage account to my VNET but I only had a private endpoint for the blob part ("privatelink.blob.core.windows.net"). Adding one for the table part ("privatelink.table.core.windows.net") solved the issue.

**Comment by Hardstl** [comment]
> In my case is was a different issue. To connect to the storage account for my functions I use Access Keys so I didn't think it was RBAC releated.
> 
> I am using a private endpoint to integrate the storage account to my VNET but I only had a private endpoint for the blob part ("privatelink.blob.core.windows.net"). Adding one for the table part ("privatelink.table.core.windows.net") solved the issue.

It's the same issue as you get access denied when it tries to purge the table logs (or whatever it's trying to do), but it can't do that as the storage account has public access denied. Functions only require Blob and File PE on the storage account, which has always been the case, so this new bug forces functions to also require the Table PE for storage accounts.

**Comment by RichardCutmoreTDS** [comment]
Is this being worked on? Our logs are filled with these. Even downgrading hasn't fixed the issue.

**Comment by pieterh** [comment]
Also would like to know this. A week or two ago, only one function in one env was on the new runtime, but now they are all on the new runtime. It is now more difficult to spot real problems since the logs are filled with exceptions..

**Comment by kbalakumar1** [comment]
We have been facing this error as well recently which is quite flooding our app insights logs. We tried implementing the suggested approach from this thread of setting the _AzureWebJobsFeatureFlags=DisableDiagnosticEventLogging_ in the app settings of the function app. This is how it currently looks like for us:

![Image](https://github.com/user-attachments/assets/fd96498a-6574-4825-8cb8-1c32917d0865)

Even after adding this setting, we are still seeing the same exceptions in our app insights logs. Could someone help on what we could be missing here please? Thanks in advance.

**Comment by mdezeeuw-visionplanner** [comment]
Adding private endpoints for table solved the issue for us. Thank you!

**Comment by mike-f50** [comment]
> [@nzthiago](https://github.com/nzthiago) the workarounds I provided will prevent it from going to app insights. The linked PR by [@cjaliaga](https://github.com/cjaliaga) ([#10996](https://github.com/Azure/azure-functions-host/pull/10996)) will also greatly reduce the volume of telemetry emitted here. The diagnostic events feature will self-disable in this scenario (no permissions)

Hi.  I can see that this PR has been merged, but we are still seeing these logs.  Is that because we are waiting for a new functions runtime version to be released and/or rolled out?  I don't suppose you are able to predict when that is likely to happen?

Many thanks.
