### ISSUE TITLE
can configure otel service name

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/azure-functions-host#11425]
#### What problem would the feature you're requesting solve? Please describe.
Our function name are a bit meaningless and we use `OTEL_SERVICE_NAME` to override the value of `service.name` in the isolated worker process.
Unfortunately, `FunctionsResourceDetector` use `WEBSITE_SITE_NAME` which is a read-only settings.
https://github.com/Azure/azure-functions-host/blob/64bc0b3e56aedd06a4a5b0a79dc7a2daa66b7695/src/WebJobs.Script/Diagnostics/OpenTelemetry/FunctionsResourceDetector.cs#L18

When searching transaction in appInsights, we have two differents values for the service name depending the source of the trace (host or worker).

#### Describe the solution you'd like
Provide a configurable setting to override the WEBSITE_SITE_NAME. For example, the worker use `WEBSITE_CLOUD_ROLENAME`

https://github.com/Azure/azure-functions-dotnet-worker/blob/ab7b3f25a6cd706aa9906c11b2feced98f59e273/src/DotNetWorker.ApplicationInsights/Initializers/AppServiceOptionsInitializer.cs#L9

**Comment by scrocquesel-ml150** [comment]
As additional context, be aware that the Azure Portal is using WEBSITE_SITE_NAME for the invocation logs page. So, invocations do not show up anymore. This is already the case when `telemetryMode` is `ApplicationInsights`.

**Comment by claria** [comment]
Hi, 
we are also affected by this unfortunate design since our switch to OpenTelemetry (we use the python worker):

- Since only the OTEL_SERVICE_NAME is used, host related telemetry cant be differentiated between slots.
- **OTEL_SERVICE_NAME** is just ignored
- **OTEL_RESOURCE_ATTRIBUTES** setting **service.namespace=my-namespace** leads to rolename set to [my-namespace]/function-app-name while on the python worker leads to my-namespace.function-app-name


For us this really is a showstopper in completely switching to opentelemetry based tracing/logging in Azure Functions.

**Comment by claria** [comment]
Hi, i think this is also related to this issue (https://github.com/Azure/azure-sdk-for-python/issues/44121) in the way that all these issues needs to be resolved in a consistent way both on the host and the worker side.

@RohitRanjanMS

**Comment by liliankasem** [comment]
This was resolved by https://github.com/Azure/azure-functions-host/pull/11506 and released in v4.1047.100 (2026-01-30) onwards

**Comment by ghost** [comment]
Hi,

Do we know when the core tools and docker image (the one I found doesn't seem to have this update) will be updated to support this version of the host?

I did try `4.1048.100-0-dotnet-isolated10.0` image located here https://mcr.microsoft.com/v2/azure-functions/dotnet-isolated/tags/list, didn't seem to fix the `Worker` service name, only the `Host`.

I am using the Aspire AppHost with local testing if that helps:

<img width="604" height="333" alt="Image" src="https://github.com/user-attachments/assets/febc9dc4-76de-4afb-a876-0d0e4ea9e5e7" />

**Comment by buzzaII** [comment]
Hi Team,

@liliankasem and @RohitRanjanMS this looks like it needs to be updated in this package as well: `Microsoft.Azure.Functions.Worker.OpenTelemetry 1.1.0`

https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.OpenTelemetry/FunctionsResourceDetector.cs

This is responsible for the worker 'service name' which as you can see from the previous screenshot is not picking up the standard OTEL_SERVICE_NAME.
