### ISSUE TITLE
LeaseLostException & WebException on Scale-Out

### ISSUE THREAD

**Issue by m1nkeh** [Azure/azure-functions-host#3212]
#### Investigative information

Please provide the following:

- Timestamp: 30-07-2018 23:00:00 UTC
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: wbch-dev-core
- Function name(s) (as appropriate): Testmatcher / TestCleaner
- Invocation ID: N/A
- Region: North Europe

#### Repro steps

1. Create an empty Azure v1 Function w/ EventHub Trigger
2. Deploy to Consumption Plan
3. Provision EventHub with 32 partitions.
4. Load EventHub w/ 50,000 events
5. Watch scale-out raise exceptions for LeaseLostException, and WEbException repeatedly

#### Expected behavior

According to this post: https://stackoverflow.com/questions/51602965/azure-eventhub-function-leaselostexception#51603421

These should be tracked as warnings in the latest host deployment?

#### Actual behavior

Tracked as exceptions

#### Known workarounds

None

**Comment by m1nkeh** [comment]
7 days, any acknowledgement? :(

**Comment by lukasvosyka** [comment]
+1 for fixing

**Comment by m1nkeh** [comment]
clearly not fixed yet???

**Comment by garygsscott** [comment]
+ 1 for fixing.    Any ETA?

cc: @tohling

**Comment by m1nkeh** [comment]
![image](https://user-images.githubusercontent.com/13475141/53053321-ebf6bc80-3498-11e9-9641-26cef8243abc.png)

**Comment by m1nkeh** [comment]
![](https://vignette.wikia.nocookie.net/irategamerdoesnotsuck/images/2/2f/Tumbleweed.gif)

**Comment by fabiocav** [comment]
Sorry about the delayed response here. To confirm the impact, this is primarily generating noise in the logs, correct? Those exceptions are normal, and handled by the runtime, but currently still tracked/logged. Some improvements were made in 2.0, so it would be interesting to understand if the behavior there is satisfactory.

@tohling were there any other open work items related to this?

**Comment by fabiocav** [comment]
Actually, the issue linked to the SO question referenced in the original issue was resolved with PRs linked to https://github.com/Azure/azure-webjobs-sdk/issues/1760

@m1nkeh can you confirm?

@garygsscott if you're seeing similar exceptions, can you please open a different issue and share details/stack?

Thanks!

**Comment by m1nkeh** [comment]
i keep meaning to reply to this.. but i am working with a brand new project, with all the latest up to date SDK levels, Azure Functions 2.0 .Net Core etc.. etc..

Host level exceptions (all of them) are annoying noise in Applicaiton Insights.. this particular one, relating to the lease lost stuff is especially frustrating because under heavy load / scaling there are just constant exceptions and everyone on my team just 'knows' they are fine, and ok to ignore.

Why not just change these to warnings? The number of times i have to explain why these are ok to ignore with a diagram, and explanation of event hubs, and leases is just a massive time sink.

**Comment by garygsscott** [comment]
Hi @fabiocav, @m1nkeh - I managed to suppress 90 % of these warning messages in my function by creating a dedicated consumer unit within my event hub and then ensuring that my event hub triggered function only connected to that one particular consumer unit.    These messages still appear but with much less frequency after taking this approach.   I actually work for the same organisation as @m1nkeh so do not believe a new case is justified and I agree with @m1nkeh that if these are not blocking exceptions and just warnings then shouldn't they be suppressed (to reduce the noise in troubleshooting more than anything else).

**Comment by charlesYong076** [comment]
+1 for fixing

**Comment by brettsam** [comment]
This has been fixed with https://github.com/Azure/azure-webjobs-sdk/pull/2176. The next version of the EventHubs package will contain the fix.
