### ISSUE TITLE
Consumption plan: Inactivity Service Bus Topic Trigger not firing

### ISSUE THREAD

**Issue by jwisener** [Azure/azure-functions-host#4671]
We currently are running v2 of azure functions, specifically for azure service bus to process topic/subscriber messages. We are doing development with visual studio 2019 and running in a "windows platform" (both locally and in azure), so everything is pretty much out of the box. We publish the functions using CI (azure devops). We use the azure tasks (provided) for deploying our released artifacts. We are using the consumption plan for azure functions. 

The issue that I am seeing is: after a certain amount of time has elapsed of **inactivity**, our functions no longer seem to **trigger** when new messages arrive on the topic/subscription. I see in the azure service bus explorer they are waiting to be processed. 

If I login into the portal and go to the az-function app, and click monitor say, for a given function it seems to start working. 

#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by kashimiz** [comment]
Hi @jwisener, thanks for reporting this issue. In order for us to investigate things from our end, we'll need more information about your function app. Could you please provide the information requested by our issue template, particularly the **Investigative Information** section?

**Comment by jwisener** [comment]
Thank you @kashimiz greatly appreciated. I think I have a theory what maybe happening, and I am trying something. We come from background of writing alot of .net core applications, and we have standardized the way we do our configuration settings for all our connections strings (blob, azure service, sql server, table storage, etc...) So, as we have ventured in to replacing our current webjobs, with azure functions. I used our standardized appsettings.json format. So I was able to put in the ServiceBusTrigger attribute something like ["ConnectionString:AzureServiceBus"]. And it works (at least initially). I guess I did not think about the other side what is called the "scale controller", it is probably looking for an exact key name of "AzureWebJobsServiceBus" which in my case I removed in order to try and keep our development standardized.

**Comment by fabiocav** [comment]
@jwisener are you actually updating the configuration to use an appsettings.json file? If so, this is, unfortunately, something the scale controller won't be able to consume, so it won't have those settings. For the connections strings used by triggers, those would need to be set as App Settings for your Function Apps

**Comment by jwisener** [comment]
@fabiocav , no it’s not a direct update. I take the design of our current app settings/connection strings and get it in the form that azure functions needs. I set those settings in the azure portal for our  appsettings and connections strings appropriately. For us, Azure servicebus is a connection string, just like sql, blob, table and so forth. Azure functions decided to do things differently and treat azure servicebus connection string as an app setting. 

We use strongly typed objects to hold our settings. This way we can validate them before any .net core process starts and ensure all settings are provided and eliminates magic strings from our code base. These setting objects are then injected into our various constructors that need them and thus resolved by DI. We have a lot of code that does it this way today, i fact we have been doing this even pre .net core.

Why azure functions decided to do things differently outside of the established patterns set forth in .net core concerning appsettings.json is a bit perplexing. We use appsettings.json as recommended by Microsoft in the .net core ecosystem such that we can target and release to different environments. Without having to login to every environment and enter (by hand) every setting. Yes, I know I could set an arm template, but now I will have to and modify all our current CI builds/releases.  But that is fine I will just have to go and set them all by hand to start. 

The appsettings.json gives the ability to override settings when needed. Azure functions does not (or if it does, I can’t find any docs on it), you basically have a ‘name value scheme’. It’s not optimum, but I can at least use the ‘:’ in the name part to still consume the setting and project it into our strongly types objects without having to rewrite everything. However moving to azure functions we have lost the ability to override. And it seems the ability to designate to azure functions which one of our connections strings is for azure service bus is not possible (at least for consumption)

It seems limiting to me and reduces scalability by having only one azure service bus connection string and azure has harded coded the ‘scaler process’ such that it can be only one value. What if I needed to connect to multiple azure service bus instances. I don’t think that is possible given the current ‘scalar’ design. It would be better if we could designate which function to which service bus account. You somewhat support this by giving us a connection parameter. I can point that to different servicebus connections if I wanted to. The problem seems to be for consumption, you can only have one and it must the one specified in appsettings with a specific name. Or is there another way to tell the scaler ‘hey watch for messages on these multiple service bus instances’

For example, we connect to many different blob storage accounts, but thankfully as of now we only have one azure service bus.  But if I wanted to trigger off off multiple blob accounts (using consumption) is that possible?

Hopefully that makes sense. Perhaps there is a better way and I am just missing it. 

Don’t get me wrong I like azure functions, i am just coming from .net core and it’s been not been straight forward and requires trial and error to figure things out as the documentation is a bit lacking or too brief. I try to find resolution to issues I hit, But it’s tough when what you find on github are issues that are have been open from 2017, so it’s hard to know what has been fixed, or what is still being worked on, or maybe even abandoned.  For example, trying to use DI with our existing code base. Scoped factories are broken such that would if i went forward, it would have caused database corruption, as it was injecting new dbcontexts instead of adhering to what was specified in the startup. But that is another issue all together.

Thanks for all you guys do!

**Comment by jwisener** [comment]
https://github.com/Azure/azure-functions-host/issues/4671#issuecomment-511554530

**Comment by jwisener** [comment]
@fabiocav is it possible to see the source code for the scaler process?

**Comment by fabiocav** [comment]
There are a lot of historical reasons for the current behavior, but that pre-dates .NET Core and the configuration model supported there. That is all based on the WebJobs functionality and, though the runtime itself could be updated to use the appsettings.json (which is something we do intent to do), there are infrastructure pieces that still have a dependency on the previously existing model that would need to be updated as well.

As far as the ability to override configuration, you can do that (using the same conventions  you'd find in .NET Core), which enables you to configure anything that would go into `host.json` using App Settings (which is something we expect to support with appsettings.json) as well.

For the concerns you've brought up above, multiple connection strings (for multiple triggers and input/output bindings) are supported. You can specify the connection string to be used as part of the binding configuration (bindings expose a `connection` setting, when applicable, allowing you to specify the connection you want to use). You can find the full documentation here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-storage-blob-triggered-function

Unfortunately, the scale controller code is part of the App Service infrastructure, which isn't open source.

Also, about @kashimiz's request above; you can share your function app information privately using the information here: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately

**Comment by jwisener** [comment]
Thanks for the information, @fabiocav  that is very helpful and i really
appreciate you taking the time to provide detailed information.

I’ve opened support case with Microsoft to try and figure out why the azure
servicebus functions are not triggered when new messages arrive on a
subscription queue. After the functions go idle, perhaps they can help
provide some guidance on what the issues maybe.

Perhaps it’s because we store the azure service connection string in the
connection strings section, instead of making it an application setting.
Hard to really know since i can’t see the code for the scaler.

Do you know what would happen if the azure service  connection string was
stored in the connection sections instead of the app settings section?

I know at least when we deploy and after we sync, they work. But then they
never trigger after going idle. Do you think the scaler code is looking in
the app settings section for the name i have given the connection
parameter? It would be great if az function trigger gave a warning or even
threw/logged some type of error, that I could see.

If that is the case, then I will need to rework our existing code and
strongly typed settings to work with two different types of configurations,
one we use when we write/maintain our .net core apis and another for azure
functions. Which i can do, but before I go down that path, it would be nice
to know, if that is the case.

Kindly,
Jason

**Comment by fabiocav** [comment]
We are working on surfacing scale controller logs so you're aware when things like that happen. Some of that already happens today when you go through the diagnostics (detectors) section of the portal.

What is added to connection strings is setup under the "connection strings section" of the configuration. If you're referencing them without the "ConnectionStrings" section prefix, it is indeed possible the scale controller is not picking those up and failing to keep your site active. With basic app information, we can confirm whether that is the issue.

**Comment by jwisener** [comment]
@fabiocav  Id=7db0fa5d-f37f-43d0-b844-b3a3b987564d

**Comment by fabiocav** [comment]
That may explain the issue. The connection string prefix added by App Service uses the double underscore delimiter (`__`), and most likely what the scale controller is looking at is `ConnectionStrings__<name>`.

I'll be able to verify when in the office using the ID you've provided, but would also need a region and approximate timeframe to look at. In the meantime, you can try using `ConnectionStrings__<name` in the connection parameter to see if that helps.

**Comment by jwisener** [comment]
Okay, I'll get that a try.

In Region EastUS:

Start CST DateTime: 7/16/2019  13:00:00 CST or 7/16/2019 18:00:00 UTC
End CST DateTime: 7/16/2019 13:55:00 CST  or 7/16/2019 18:55:00 UTC


The __ Doesn't work too well when dealing with local.settings.json and
trying to run locally.

**Comment by fabiocav** [comment]
Not sure if you verified this, but your best option might actually be to move those connection strings to app settings instead. One advantage is that you can use the `ConnectionStrings:` prefix there as there is no other prefix added by the infrastructure.

**Comment by jwisener** [comment]
we have a lot of other .net core apps we would have to go thru and change to accommodate that. But i did verify, it has to be in app-settings section. Or else it never triggers after it goes inactive. The ___ makes it hard run locally in our dev environments for local settings. I was thinking maybe I can set what I need via the webjobbuilder instance at startup. We make heavy use of the appsettings.json specifically that section. I guess if .net core api’s we’re recommending and going in this direction we would consider moving them

**Comment by fabiocav** [comment]
You shouldn't need to use `__` if using app settings, the colon delimiter would work (though, .NET Core will handle both delimiters).

**Comment by fabiocav** [comment]
Closing this as I believe we now understand what was happening and how to deal with it, but let me know if you feel this isn't the case. And thanks for providing the additional information requested and testing so quickly! That was very helpful.

**Comment by jwisener** [comment]
Thanks @fabiocav!
