### ISSUE TITLE
Dependency Injection issue: Unable to resolve service for type ... while attempting to activate [TimerFunction]

### ISSUE THREAD

**Issue by adamgd** [Azure/azure-functions-host#4939]
Injecting a DocumentClient instance works fine when debugging a Function locally but not on Azure. Possibly the same symptom as #4187.

#### Investigative information

Please provide the following:

- Timestamp: 2019-09-17 11:30:00.006
- Function App version (1.0 or 2.0): ~2
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 1a2d55843b4483409d843976bb3b7fdf
- Region: UK South

#### Repro steps

Configure DocumentClient as a service:

    public class Startup : FunctionsStartup
        {
            public override void Configure(IFunctionsHostBuilder builder)
            {
                builder.Services.AddSingleton<IDocumentClient>(s =>
                    new DocumentClient(new Uri(GetEnvironmentVariable("DatabaseAcctEndPoint")), GetEnvironmentVariable("DatabaseAcctKey") ));
            }
        }

... and then inject:

    public class TimerClass
    {
        [snip]
        private IDocumentClient _documentClient;
        
        public TimerClass(IDocumentClient documentClient)
        {
            _documentClient = documentClient;
        }

#### Expected behavior

The above code works fine when running in Debug locally (whether connecting to CosmosDB emulator or Azure-hosted CosmosDB) but not when the *function* is hosted on Azure.

#### Actual behavior

Exception thrown:

```
System.InvalidOperationException:
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService (Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at lambda_method (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 37)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 32)
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1+<>c__DisplayClass1_1.<.ctor>b__0 (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 20)
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 26)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 44)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+ParameterHelper.Initialize (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 846)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsyncCore>d__16.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 117)
```

#### Related information 

I think this is the same as, or similar to, #4187. As @fabiocav suggested at the end of that issue, I'm opening this as a new issue.

**Comment by ThatBlokeCalledJay** [comment]
I've just started getting the same issue locally.

![image](https://user-images.githubusercontent.com/9808053/65394990-98c94d00-dd8c-11e9-8d29-960456f8e7f2.png)

I deployed the function about a month ago (it's still deployed and running). I've just opened up the code in VS2019, hit run to test locally and am getting the DI service not found exception. No code changes were made, and I haven't updated my nuget packages? 

![image](https://user-images.githubusercontent.com/9808053/65395014-05dce280-dd8d-11e9-9b9e-e2df983e4157.png)

![image](https://user-images.githubusercontent.com/9808053/65395019-1ab97600-dd8d-11e9-80c5-2f88d64ce873.png)

Any ideas.

**Comment by fabiocav** [comment]
@ThatBlokeCalledJay would it be possible to share a repro so we can take a closer look at your function and registration?

I've noticed you're missing version 2.33.0, which was a preview with a resolution fix for validation. Have you tried to follow the instructions [here](https://github.com/Azure/azure-functions-host/issues/3399#issuecomment-518855094) ?

**Comment by fabiocav** [comment]
@adamgd can you please validate with the steps linked above as well?

**Comment by ThatBlokeCalledJay** [comment]
Hey @fabiocav yes, of course. bare with me.

**Comment by ThatBlokeCalledJay** [comment]
I didn't need to publish the full repo, I quickly created supper skinny test, which also fails exactly the same as above.

https://github.com/ThatBlokeCalledJay/azure-function-di-test

If I simply run that guy up and hit the endpoint suggested from a browser 

http://localhost:7071/api/Function1

![image](https://user-images.githubusercontent.com/9808053/65699751-74b08900-e076-11e9-9b8e-a1ac0dbf506b.png)

So as above, but with this super skinny function.

I created this guy, like so:

![image](https://user-images.githubusercontent.com/9808053/65699849-9f024680-e076-11e9-8321-ebce2b53104b.png)

![image](https://user-images.githubusercontent.com/9808053/65699917-b6413400-e076-11e9-9c38-be6da89b3c2c.png)

**Comment by ThatBlokeCalledJay** [comment]
> @ThatBlokeCalledJay would it be possible to share a repro so we can take a closer look at your function and registration?
> 
> I've noticed you're missing version 2.33.0, which was a preview with a resolution fix for validation. Have you tried to follow the instructions [here](https://github.com/Azure/azure-functions-host/issues/3399#issuecomment-518855094) ?

So here's me doing that ^^^

![image](https://user-images.githubusercontent.com/9808053/65702068-48970700-e07a-11e9-9d27-519f4ed9e580.png)

So far so good...

![image](https://user-images.githubusercontent.com/9808053/65702253-9b70be80-e07a-11e9-875e-142263306a40.png)

Swish...

![image](https://user-images.githubusercontent.com/9808053/65702496-06ba9080-e07b-11e9-8a6d-68e7f56fea28.png)

No whistle, nore bells...

![image](https://user-images.githubusercontent.com/9808053/65702629-41242d80-e07b-11e9-87b5-1368c42da527.png)

H-ok... let's do this

![image](https://user-images.githubusercontent.com/9808053/65702832-97916c00-e07b-11e9-8d91-7797c790dd99.png)

Sad times...

**Comment by adamgd** [comment]
I have just tried a simple case like the one posted by @ThatBlokeCalledJay  above, after following the instructions posted by @fabiocav. The only significant difference is that mine is a Timer Trigger. The function works with simple injected Singleton service class both locally and on Azure.

![image](https://user-images.githubusercontent.com/651392/66144259-688d7400-e600-11e9-8250-d02d2ef0339a.png)

Result of hitting url ```https://<functionappname>.azurewebsites.net/admin/host/status?code=<masterkey>```:

```
    {
    [snip]
    "state":"Running",
    "version":"2.0.12620.0",
    "versionDetails":"2.0.12620.0
    [snip]
    }
```
I will try to deploy my applied function against the same preview and report how it goes.

**Comment by T-rav** [comment]
I had the same problem. I fixed it by **REMOVING** the **Microsoft.Azure.Functions.Extensions** NuGet package. As soon as I did this I can debug locally and IoC works.

**Comment by kevinphelps** [comment]
I am having this issue after updating to AzureFunctionsVersion v3. It worked fine with v2. Is there another issue tracking v3 dependency injection issues or is that covered by this issue?

**Comment by fabiocav** [comment]
@kevinphelps there are a few different issues here and many around issues prior to GA.

Can you please open another issue with the details of what you're seeing?

**Comment by kabirshaikh** [comment]
I am having this issue as well. More specifically, it works locally, but fails on Azure. I have tried the various proposed solutions mentioned in this thread, but nothing has worked. Is this issue being worked on?

**Comment by jonathanantoine** [comment]
Same issue and behavior than @kabirshaikh . Any help would be appreciated.

**Comment by fabiocav** [comment]
@kabirshaikh @jonathanantoine can you please open a separate issue with the details of the error you're seeing, including the runtime version you're using? If you have a repro you can share, that would be great!

**Comment by fabiocav** [comment]
@adamgd just wanted to check if this is something you're still seeing with your setup. Can you please confirm?

**Comment by ThatBlokeCalledJay** [comment]
This hasn't gone stale and certainly shouldn't be closed. I've been waiting quietly for a resolution. I dont see any resolutions posted on this thread and recent testing is still failing.

**Comment by fabiocav** [comment]
@ThatBlokeCalledJay are you seeing the problem with the same setup as described in the original issue? Would you mind opening a separate issue with the details of what you're seeing and a repro?

**Comment by shraddhaagrawal** [comment]
Any Update on this?
I am facing same issue

**Comment by shraddhaagrawal** [comment]
We were facing same issue for version 2.0.12961.0 and issue got resolved after updating default host.json

Before-
`{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}`

Working-
`{
  "version": "2.0"
}`

**Comment by paonekumar** [comment]
it is working after removing extensionBundle from  host.json, but looks like it is impacting performance

**Comment by adiazcan** [comment]
It's working also for me, removing extensionBundle and version 1.* fix the problem. 

One question, Why the host file has this options? I have a blank host.json on my project and something generate this wrong content

**Comment by shraddhaagrawal** [comment]
@adiazcan This is default host.json
You have to change properties of host.json file to copy always.

**Comment by noant** [comment]
I found that if IWebJobsStartup.Configure method is async and there is awaitable calls in this method, then "Unable to resolve service for type..." exception is thrown.

Not works:
`
public async void Configure(IWebJobsBuilder builder)
{
    var backupConfiguration = await configurationReader.ReadConfiguration<BackupConfiguration>(configurationName);
    new Startup().Configure(builder.Services, backupConfiguration);
}
`

Works:
`
public async void Configure(IWebJobsBuilder builder)
{
    var backupConfiguration = configurationReader.ReadConfiguration<BackupConfiguration>(configurationName).Result;
    new Startup().Configure(builder.Services, backupConfiguration);
}
`

**Comment by kabirshaikh** [comment]
I have tried all of these solutions and it is still not working for me. This should **NOT** be closed.

**Comment by briandunnington** [comment]
Removing the extensionBundles from host.json like @shraddhaagrawal suggested solved it for us. Any idea on why this behavior changed recently? Took a long time to stumble upon this GitHub issue and solution.

**Comment by jenol** [comment]
I started having this issue after upgrading Microsoft.NET.Sdk.Functions to 3.0.3. Downgrading to 1.0.31 fixed the problem for me. I hope it helps.

**Comment by briandunnington** [comment]
@fabiocav This has been having huge impacts on use. We have v2 functions that have been running for months with no deployments that started breaking. The host.json file has been modified to
```
{ "version": "2.0", "extensionBundle": { "id": "Microsoft.Azure.Functions.ExtensionBundle", "version": "[1.*, 2.0.0)" } }
```
and it caused these 'Unable to resolve service for type...' errors. Manually editing the host.json back to just `{ "version": "2.0" }` solved it, but it took forever to figure out what the cause was. The worst part is that the portal showed that the functions were started and running the whole time so we didn't know that the service was not starting properly.

What was the reason for the change? Should we expect it will happen to all of our services?

**Comment by ThatBlokeCalledJay** [comment]
> @ThatBlokeCalledJay are you seeing the problem with the same setup as described in the original issue? Would you mind opening a separate issue with the details of what you're seeing and a repro?

@fabiocav of course I am. You'd like me to copy the verbose information + pictures + link to an example repo I posted above to a new thread? 90% of all information on this thread has been provided by me, heaps of info, images and the requested repo. I think a better idea would be for you to re-open this thread as it should never of been closed in the  first place. I am having exactly the same issue now as I was having when I detailed my first issues.

I've already put in the leg work trying to detail as much as I can to help resolve the issue. Sorry if I didn't keep poking the thread every 15 minutes to keep it alive.

**Comment by JVaughan1978** [comment]
I've just gone a round with this issue @ThatBlokeCalledJay and I believe that what you might have ran into but not realized it was actually a configuration with your csproj file you probably needed to include something akin to this: 
`    <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    </ItemGroup>`

Most likely your host.json and local.settings.json weren't propagating and if you get the auto generated host.json it will error out on Dependency injection.

**Comment by ThatBlokeCalledJay** [comment]
Thanks @JVaughan1978 Exciting stuff, I'll give that a whirl.

**Comment by ThatBlokeCalledJay** [comment]
Ok, so I've just created an azure unction using sdk 3.0.3 and all seems to be working fine. I don't have that much invested where I can't just shift/upgrade my functions so I'll just do that do that.

**Comment by bobwah** [comment]
works for 3.0.3 after updating to 3.0.4 no longer hitting breakpoints and receiving the dependency injection error above.

**Comment by rmbrunet** [comment]
Same as @bobwah, simplest solution works well locally with sdk 3.03 but not with sdk 3.0.4!

**Comment by ThatBlokeCalledJay** [comment]
🤦🏻‍♂️

**Comment by Dave76** [comment]
I also wanted to confirm that DI is busted with 3.0.4 sdk. Works fine with 3.0.3.  I just had to downgrade my new solution in order get DI working.

**Comment by ilushka85** [comment]
Di working fine in 3.0.3 for us... updating to 3.0.4 breaks it.

**Comment by jasonshave** [comment]
I can also confirm the same. Fought with this for the past day or two and finally found this post. Downgraded to 3.0.3 and it works again!

**Comment by petrsx** [comment]
seems like this has been fixed in 3.0.5 released yesterday

**Comment by nmaroine** [comment]
@petr-x no, I'm still having the same problem ...

**Comment by rmbrunet** [comment]
I'm OK in 3.0.5

**Comment by lvnre** [comment]
Encountering the same DI error. Upgrading from 3.0.1 to 3.0.5 did not resolve the error. **Removing extensionBundles from bin/Debug/netcoreapp3.1/host.json did resolve the error**

**Comment by petrsx** [comment]
@Invre Actually it is combination of both. **Upgrade to 3.0.5 and remove the ExtensionBundles**. Tested with 3.0.4 without bundles it didn’t worked.

**Comment by rameshjanjyam** [comment]
> I found that if IWebJobsStartup.Configure method is async and there is awaitable calls in this method, then "Unable to resolve service for type..." exception is thrown.
> 
> Not works:
> 
> ```
> public async void Configure(IWebJobsBuilder builder) // async method
> {
>     var backupConfiguration = await configurationReader.ReadConfiguration<BackupConfiguration>(configurationName);
>     new Startup().Configure(builder.Services, backupConfiguration);
> }
> ```
> 
> Works:
> 
> ```
> public void Configure(IWebJobsBuilder builder) // non-async method
> {
>     var backupConfiguration = configurationReader.ReadConfiguration<BackupConfiguration>(configurationName).Result;
>     new Startup().Configure(builder.Services, backupConfiguration);
> }
> ```

this helped in my case. I have `async`  lambda and it didn't work. removing `async` (& await) helped 
```
builder.Services.AddSingleton(async sp =>
            {
                var config = sp.GetService<IConfiguration>();
                var client = new CosmosClient(config["COSMOS_CONNECTION_STRING"]);

                await client.CreateDatabaseIfNotExistsAsync("eventstore", 400);
                await client.GetDatabase("eventstore").CreateContainerIfNotExistsAsync("app", "/id");
                return client;
            });
```
