### ISSUE TITLE
Debug startup fails "no Function runtime available"

### ISSUE THREAD

**Issue by zpittmansf** [Azure/azure-functions-host#5145]
#### Investigative information

Please provide the following:

- Timestamp: 
- Function App version (1.0 or 2.0): 3.0
Visual Studio 2019 16.3.6

#### Repro steps

Provide the steps required to reproduce the problem:

Start project in debug mode locally. 
Immediately a Microsoft Visual Studio Error appears - "There is no Functions runtime available that matches the version specified in the project."

Here is the csproj properties, as far as I know this has not changed since it was working last.
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Kafka" Version="1.0.0-alpha" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

#### Expected behavior

It builds fine, it should startup at least.

#### Actual behavior

Fails to startup or even enter the azure function prompt.

#### Known workarounds

None

#### Related information 

Provide any related information 

* Programming language used - C#
* Links to source - N/A simple project on local

**Comment by michaeldaw** [comment]
I'm also having this issue. I went through the steps detailed [here](https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm), but I don't see Azure Functions v3 Preview in the list of available templates:
![image](https://user-images.githubusercontent.com/8949148/67513144-752d4700-f657-11e9-8cff-8a30be7b10e2.png)
I tried running a function app that was created in the v3-preview on another machine, where it worked as expected, but I get the error mentioned by @zpittmansf on my current machine. It seems like it can't find the v3 preview template(s).

**Comment by zpittmansf** [comment]
@michaeldaw I just tried to create a fresh project and even though yesterday it worked today I have the same result. 
![image](https://user-images.githubusercontent.com/56922842/67513638-3bfdd280-f669-11e9-9038-92262bc2fdc1.png)

I double checked that the environment variable is in place as well.
![image](https://user-images.githubusercontent.com/56922842/67513678-5637b080-f669-11e9-8af4-10dd8e4a371a.png)

**Comment by michaeldaw** [comment]
Actually, I could have sworn it was working yesterday as well. Maybe something has changed?

**Comment by zpittmansf** [comment]
Latest commit was 7 days ago on the master branch, I don't see any releases in github that match beta version listed here, not sure why?
https://github.com/Azure/azure-functions-vs-build-sdk/commit/ca38d6b097960949887642b351d4c10625c3ae80

**Comment by michaeldaw** [comment]
It seems that the entry for v3-preview in the `C:\Users\[user]\AppData\Local\AzureFunctionsTools\feed.json` file is automatically deleted when you start visual studio and try to make a new function project.

**Comment by zpittmansf** [comment]
I can confirm that is the same for me. @michaeldaw how did you figure that one out?

**Comment by zpittmansf** [comment]
https://github.com/Azure/azure-functions-tooling-feed/commit/ddc1e1992b876f456a6288bf189cce9243fa2243 just changed yesterday

**Comment by zpittmansf** [comment]
@michaeldaw if you want to still run and debug I was able to get this started by opening cmd/powershell to the root of my project then running func.exe start:
`C:\temp\projectroot\> C:\Users\[user]\AppData\Local\AzureFunctionsTools\Releases\3.0.2\cli\func.exe start`

**Comment by a-vishar** [comment]
Followed [these instructions](https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm), unable to see any V3 options in the dropdown and when I try to run an existing project with a manual upgrade I get the  "There is no Functions runtime available that matches the version specified in the project." error.

**Comment by michaeldaw** [comment]
@zpittmansf very nice, thanks for the tip. Hopefully this gets sorted out soon.

**Comment by mhoeger** [comment]
@soninaren - could you comment on this issue?
cc: @brettsam

**Comment by pavitrag123** [comment]
Hi,

Any update on this issue. I upgraded my azure v2 functions to v3 yesterday and they were working fine. Suddenly since today morning I'm not able to run my functionapp solution. Facing same error "no Function runtime available". 

My feed json doesnt have v3 version in it though I ahev version 3 folders in my Releases folder. Updating it manually is getting overridden when visual studio is opened. 

Yesterday I upgraded my VS2019 version to 16.3.6. Not sure if issue is because of this or something  else. Any help would be appreciated

**Comment by soninaren** [comment]
This should be fixed now. Please close and re-open visual studio.

**Comment by michaeldaw** [comment]
Thank you @soninaren. It seems to be working for me. 
FYI for others: when I first opened visual studio to create a project, I didn't see the v3-preview option right away. I had to wait for the "updating templates" message to complete, then clicked Back, and created the project again. At that point, v3-preview was visible.

**Comment by zpittmansf** [comment]
@soninaren what was the fix? I am just curious.

**Comment by soninaren** [comment]
We needed to update the feed so that it aligns with different versions of visual studio. We misinterpreted which function release version would map to which version of VS effectively causing the v3-preview disappear.

**Comment by jagge123** [comment]
> We needed to update the feed so that it aligns with different versions of visual studio. We misinterpreted which function release version would map to which version of VS effectively causing the v3-preview disappear.

Still not working for me :/

**Comment by Shrn-Prmshr** [comment]
It has been started to happen for me since today morning (I did not have any problem before that. I updated my VS 2019 to 16.2.9, nothing has been changed). I do not know if I should trust this preview or not. I need to push my code to production as soon as possible.
Can someone from the team give me a proper answer?

**Comment by kristofferjalen** [comment]
@Shrn-Prmshr and @jagge123 Now you have to use Visual Studio 2019 **Preview 3 or 4** (previously you could use other versions, but as of Nov 11 it must be Preview 3 or 4). They changed the instructions in the [blog post](https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm).

**Comment by dirq** [comment]
Mine stop working after I upgraded Visual Studio to 16.3.9 yesterday.  ;(

**Comment by dirq** [comment]
I just downloaded the latest VS2019 preview, and I could run the function again.

**Comment by prohith46** [comment]
Same issue for me - Any update on this ?

**Comment by Dongbumlee** [comment]
what's wrong with that? after updating VS2019, it makes trouble again. - version 16.3.9 :(

**Comment by Shrn-Prmshr** [comment]
I have downloaded VS2019 preview 4, VS2019 16.4.0. and my problem has been solved!

**Comment by Shrn-Prmshr** [comment]
@Dongbumlee download VS2019 preview 4. The VS2019 version should be 16.4.0. that will fix your problem.

**Comment by david-peden-q2** [comment]
Confirmed works with Preview 5 as well.

![image](https://user-images.githubusercontent.com/11466099/68883860-7b9f6380-06d7-11ea-9b3a-24f29d08af0a.png)

**Comment by MedAnd** [comment]
Worked once with the latest VS preview and some hours later the same issue came back as everyone above is reporting!

![image](https://user-images.githubusercontent.com/13365135/70113437-4a4dfe00-16ad-11ea-8d32-f928ab5ad6bf.png)

**Comment by brettsam** [comment]
@MedAnd -- I know we had a brief period yesterday where the VS tooling was using the wrong feed details -- you may have run across that. Can you try closing VS and re-opening it again? That should prompt it to update.

Also note that VS 16.4.0 released officially (non-preview) yesterday which has this support.

If you continue to see this I'll dive in deeper.

**Comment by MedAnd** [comment]
@brettsam - I tried with VS 16.4.0 today and it fails to launch the function project in debug mode as per above issue... to work around I had to set debug options to:

C:\Users\<user>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\func.exe

**Comment by jeffhollan** [comment]
Can you try (in 16.4.0), after setting the environment variables, clicking "File -> New Project" and going up through the template select screen?  When you get to the screen that shows templates you should see a little spinner in the bottom right saying like "Getting latest items..." or something.  Wait for it to finish.  You can then close the create window and try to run your project.  Unfortunately this create flow is the only spot right now to get VS to "check and download" the latest metadata and runtime versions, and worth doing it to make sure it's pulled the latest.

Also good to confirm when it's done and you click refresh you see ".NET Core 3" as one of the options in the template dropdown

**Comment by MedAnd** [comment]
This is what I see but when loading my project and trying debug still fails with the same issue:

![image](https://user-images.githubusercontent.com/13365135/70204605-4edde980-1775-11ea-8ba9-07c3644164ef.png)


PS. I think in your article there is a typo, I think you meant: 

> Set the environment variable AzureFunctionsHiddenTagsVisible to 1

**Comment by jeffhollan** [comment]
Yeah that "Making sure all templates are up to date" should ideally complete and you'd see a lot more templates (like queue and cosmosdb and whatnot).  That template metadata also includes the runtime versions VS needs to run

**Comment by MedAnd** [comment]
Seems one cannot try that trick twice... I get this error instead:

![image](https://user-images.githubusercontent.com/13365135/70205002-b47ea580-1776-11ea-94f6-fa8e98c6f800.png)

**Comment by soninaren** [comment]
In case you are getting constant errors, delete the following 2 folders, close all instances of VS and open VS again.
`%userprofile%\AppData\Local\AzureFunctionsTools`
`%userprofile%\.templateengine`

**Comment by wahyuen** [comment]
Is there any workaround available if we are consistently stuck on `Making sure all templates are up to date...`?? I've tried this a number of times already with rebooting and restarting VS2019 16.4 but it just seems to hang at that stage even after an hour!

**Comment by optiks** [comment]
I'm having the same issue as @wahyuen. It's stuck on `Getting information about the latest function tools...`. Any tips?

**Comment by brettsam** [comment]
@soninaren / @vijayrkn -- any ideas on this one? Seems like people are hanging while trying to update the templates?

**Comment by soninaren** [comment]
@brettsam i think i know what is causing the update failures. With 16.4 we switched to using x64 version of cli. However the x64 version of CLI being used is not minified like x86. The core tools x64 zip file is `140 mb (x64) vs 50 mb (x86)` and the same extracted is `350 mb (x64) vs 112 mb (x86)`. This would be the likely reason for hangs.

@optiks  and @wahyuen as a workaround can do the following:
1. delete `%userprofile%\.templateengine` 
2. delete contents of `%userprofile%\AppData\Local\AzureFunctionsTools`
3. download and extract the following [zip](https://github.com/soninaren/Workarounds/releases/download/1.0.0/AzureFunctionsTools.zip) file into `%userprofile%\AppData\Local\AzureFunctionsTools`

**Comment by matteotumiati** [comment]
The solution provided by @soninaren worked on my side where I experienced the same issue of the page getting stuck on `"Making sure all templates are up to date..."`.

Pay attention on the manifest JSON file though (the one inside each `Release` version folder) because it is pointing to a different user, so you may need to adjust that before opening Visual Studio.

**Comment by rpannell** [comment]
Been fighting this for days!  Between @soninaren and @matteotumiati, I have corrected a few issues with the upgrade to .net core 3.  Thanks!
