### ISSUE TITLE
Getting 404 error code from API on functions

### ISSUE THREAD

**Issue by Noituri** [Azure/azure-functions-host#5149]
Hello,
Our application is usually working just fine but from time to time we are getting nginx 404 error code. It looks like proxy is breaking(?). It's happening at random. We weren't able to find any pattern to this behavior. It usually happens after some time from starting the azure functions.

#### Investigative information
- Function App version (1.0 or 2.0): 2.0
- Region: East US

#### Repro steps

1. Start azure functions
2. Usually functions work fine. 10k requests and everything seems to be ok but after some time API will start throwing 404 error code.

#### Expected behavior

API should not return 404 error code.

#### Actual behavior

We are getting 404 error code.
```HTML
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

#### Known workarounds

`Stop` and `Start` functions.
We found out that `Restart` option is not always working.

#### Related information 

We use C# and linux

**Comment by mhoeger** [comment]
@pragnagopa - can you help weigh in on this was an issue? It looks like the same issue as #5086, which should have been resolved with the hotfix release [v2.0.12808](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12808). Was the same deployed to Linux?

cc: @divyagandhii and @fabiocav

**Comment by pragnagopa** [comment]
Yes. This does look related to recent fix we made.
@Noituri - Can you please share invocation id for failed requests? 
@divyagandhii - Please update this issue with status on roll out of the hotfix for linux stamps

**Comment by Noituri** [comment]
It looks like proxy is blocking request, so invocation id and even request insights are unavailable. Only thing that is returned from proxy/function is that html, that I provided in this issue.

**Comment by divyagandhii** [comment]
The fix for this should be deployed now on all Linux stamps.

**Comment by jacobgunnarsson** [comment]
@divyagandhii We are still experiencing this exact behaviour, but in region West Europe. It seems intermittent, so one function might return 404 for one request, and then properly process the next request.

Restarting does not work. Stopping and starting (or deploying) seems to fix the problem temporarily.

Let me know if you need more information!

**Comment by divyagandhii** [comment]
@jacobgunnarsson  Do we have an app name and a time range?

**Comment by jacobgunnarsson** [comment]
@divyagandhii Sure! I don't want to share the app name publicly so I followed the instructions [here](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately). I hope this is enough for you to find the app name. Otherwise I can share it through email.

```
Time	19:46:46
Message	Executing 'Functions.user' (Reason='This function was programmatically called via the host APIs.', Id=02990509-459b-4c33-a41d-c55443267d75)
HostInstanceId	45a3dc1c-5ae2-48bc-ac63-cd526aa95180
ProcessId	27
InvocationId	02990509-459b-4c33-a41d-c55443267d75
```

I believe the 404's occured sometime today (2019-11-08) between 15:00 and 16:00 GMT+0100. I cannot find the requests anywhere in the Azure Portal request logs (just like the issue creator) so I can't be entirely sure. It was the `user`-function that exhibited this behaviour at the time.

**Comment by divyagandhii** [comment]
@jacobgunnarsson  Thanks for reporting this issue. The 404 you experienced is not the same as the functions host issue in this thread. There is a rare issue in our platform today where sometimes requests can land on a non-existent container due to stale cache. This is very rare and should not happen again after you redeployed your app, which refreshed the cache. If you see 404s again please let me know.

**Comment by balag0** [comment]
Looks like the underlying issue is some function invocation taking longer than configured timeout which leads to the functions host shutting down. 
Opened this issue https://github.com/Azure/azure-functions-host/issues/5228 to auto recover faster.

Is the timeout expected for this function app?

  |   |   |  
-- | -- | -- | --
  | EventTimestamp | Summary | Level
  | 2019-11-08 14:05:53.4140000 | Timeout value of 00:30:00 exceeded by function 'Functions.user' (Id: '64028809-7c14-4da6-8f20-ea91be7fbb5a'). Initiating cancellation. | 2
  | 2019-11-08 14:05:53.4350000 | Executed 'Functions.user' (Failed, Id=64028809-7c14-4da6-8f20-ea91be7fbb5a) | 2
  | 2019-11-08 14:05:55.4650000 | A function timeout has occurred. Host is shutting down. | 2

**Comment by jacobgunnarsson** [comment]
@balag0 no, that is not expected. The avg. duration for the `user` function the last 30 days is somewhere between 300-500ms, it is kinda hard to tell.

**Comment by balag0** [comment]
Since this seems like a one off instance, I would recommend adding more logs to the function and open a new issue if you see the function is taking more time than expected.

**Comment by jacobgunnarsson** [comment]
@balag0 sure, but irregardless of the reason: should I expect this behaviour if a function times out?

**Comment by jacobgunnarsson** [comment]
@balag0 @divyagandhii I'm experiencing the same intermittent 404:s again, just now at 2019-11-12 09.55 GMT +1. In addition I'm getting this error in the Azure Portal:

![](https://i.imgur.com/J3vbPK2.jpg)

**Comment by balag0** [comment]
> @balag0 sure, but irregardless of the reason: should I expect this behaviour if a function times out?

Partly yes. The expected behavior is for functions runtime to shutdown if a function execution exceeds the max timeout limit. What is missing is this shutdown should have been identified and restarted by the platform. (which is the issue i linked earlier - https://github.com/Azure/azure-functions-host/issues/5228 )
Currently because of this issue, the site is assigned an inactive worker so no new worker gets assigned (based on the scale required for the app) and the only worker assigned isn't ready to serve requests leading to 404.

In the mean time , we should investigate why some invocations are taking that long. Since this is an already closed issue for a completely different bug, please open a new issue and we can look into this more.
