### ISSUE TITLE
Extensions.json not generated when using Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator 1.1.4

### ISSUE THREAD

**Issue by eliashdezr** [Azure/azure-functions-host#5747]
Taking @jeffhollan's [words](https://github.com/Azure/azure-functions-dotnet-extensions/issues/32#issuecomment-587167920) into action, this is the main issue I've seen not only on my personal projects, but elsewhere too.

### Error while running the functions via Visual Studio:
` Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type`

### Error while deployed on a brand new Function v3 app in Azure:
```cs
System.InvalidOperationException: Unable to resolve service for type 'Project.Hidden.Domain.Interfaces.Service.IAzureStorageService' while attempting to activate 'Project.Hidden.Serverless.Importacion.VerificarFunction'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 846
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 116
```
### Only working when...
If I run the project from the cli with `func start --build`, all the functions work, but it logs the following errors on the console for each function:
```log
[2020-02-18 12:30:49 AM] Error indexing method 'ImportarcionVerificarFunction'
[2020-02-18 12:30:49 AM] Microsoft.Azure.WebJobs.Host: Error indexing method 'ImportarcionVerificarFunction'. System.Private.CoreLib: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
[2020-02-18 12:30:49 AM] Function 'ImportarcionVerificarFunction' failed indexing and will be disabled.
..
..
[2020-02-18 12:30:49 AM] The 'ImportarcionFinalizarFunction' function is in error: Unable to load one or more of the requested types.
[2020-02-18 12:30:49 AM] Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

### My system setup and configurations
Everything worked fine until I migrated to .NET Core 3

```
 - Visual Studio 16.5.0 Preview 2
 - azure-functions-core-tools@3.0.2106
 - npm@v13.2.0
```
`global.json`
```json
{
  "sdk": {
    "version": "3.1.101"
  }
}
```

`.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
    <PackageReference Include="Utf8Json" Version="1.3.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project.Hidden.Data\Project.Hidden.Data.csproj" />
    <ProjectReference Include="..\Project.Hidden.Domain\Project.Hidden.Domain.csproj" />
    <ProjectReference Include="..\Project.Hidden.Services\Project.Hidden.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

`Startup.cs`
```csharp
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Project.Hidden.Data;
using Project.Hidden.Domain.Interfaces.Repository;

[assembly: FunctionsStartup(typeof(Project.Hidden.Functions.Startup))]

namespace Project.Hidden.Functions
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IAzureStorageService, AzureStorageService>();
        }
    }
}
```

`local.settings.json`
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "FUNCTIONS_EXTENSION_VERSION": "~3"
  }
}
```

`host.json`
```json
{
  "version": "2.0",
  "healthMonitor": {
    "enabled": true,
    "healthCheckInterval": "00:00:10",
    "healthCheckWindow": "00:02:00",
    "healthCheckThreshold": 6,
    "counterThreshold": 0.80
  },
  "functionTimeout": "00:10:00"
}
```

**Comment by brettsam** [comment]
@Coops9 / @eliashdezr -- you can see the fix to the targets file I've made here: https://github.com/Azure/azure-functions-host/pull/5748/files#diff-8924132f0d2b330a1888e0f17c5fcdb4

While we wait for approval/build/publish to nuget, you can try this locally if you want to verify it'll fix you -- the local file for you is in `{nuget package location}\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.4\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets`. If you change that line and rebuild, you should get the correct output.

**Comment by brettsam** [comment]
I've just pushed new versions of [Microsoft.Net.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/) to nuget. Versions `1.0.34` (for v1 and v2) and `3.0.5` (for v3) should be indexed and available shortly.

Please give those a try and let us know if you run into issues with generated extensions.json (or DI or bindings) with this package.

**Comment by brettsam** [comment]
... although now that I look back up at the original issue it was opened 17 days ago, which was before 3.0.4 had been published. Maybe there's another issue hiding behind this one. If so, @eliashdezr would you mind opening a new issue since we've repurposed this one for the build problem in 3.0.4?

**Comment by eliashdezr** [comment]
@brettsam thanks for the quick responses and effort put on resolve this quickly!

I can confirm that all the issues related with the dependency injection have been resolved, locally and deployed using the version `3.0.5` of the `Microsoft.NET.Sdk.Functions` package.

Thanks again and @jeffhollan too for jumping on this also.

**Comment by StefH** [comment]
Note that I still get an error when running a V3 function on a Linux App Service.
When deploying the same code (3.0.3 or 3.0.5) on Windows App Service, it works fine.

Anyone else noticed this same behaviour also?

**Comment by brettsam** [comment]
@StefH -- 
- Can you share your project file? 
- Can you verify that the published output is the same between windows and linux?
- What error are you getting, specifically?

**Comment by StefH** [comment]
@brettsam 
- The example project can be found here: https://github.com/StefH/AzureFunctionsV3
- The published output should be the same because I build once and then release the same zip to Windows and to Linux.
- Errors can be found here : https://github.com/Azure/Azure-Functions/issues/1518

**Comment by brettsam** [comment]
Let's follow up on the linked issue where there's more context. Thanks!
