### ISSUE TITLE
Azure Functions App (V3) reporting "There are some issues with your runtime version"

### ISSUE THREAD

**Issue by DaneVinson** [Azure/azure-functions-host#6278]
Azure Function App: V3 (Microsoft.NET.Sdk.Functions 3.0.7)
Platform: .NET Core 3.1
OS: Linux

Our Azure Functions App is reporting "There are some issues with your runtime version" in the "Overview" section of the Azure Portal's Azure Functions Blade. I cannot determine what the issue is but the host appears to be failing to start and if I browse to the site I get the message "Function host is not running." I found a similar report in this [Issue](https://github.com/Azure/azure-functions-host/issues/6046) but I've looked at all the suggestions there and do not see any issues. Here are some of the relevant appsettings:

```
APPINSIGHTS_INSTRUMENTATIONKEY = {validated App Insights instrumentation key}
AzureWebJobsStorage = {validated connection string to general purpose storage v2 account}
FUNCTIONS_EXTENSION_VERSION = ~3
FUNCTIONS_WORKER_RUNTIME = dotnet
WEBSITE_RUN_FROM_PACKAGE = 1
```

Additionally this is the contents of the host.json file which can be seen in the Function App's App Files blade:
```
{
  "version": "2.0"
}
```

This is the .csproj file for the project:
```
<Project Sdk="Microsoft.NET.Sdk">  
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.1" />
  </ItemGroup>
    <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Deployments are being done with an Azure DevOps pipeline and showing as successful both in Azure DevOps and in the Function App's Deployment Center blade.

I cannot get any logging on the application. Changes made in the App Service log blade appear to work (i.e. no errors) but they do not hold (i.e. if I leave and come back the settings are defaults again). Going to the Log Stream blade just shows the message "Connecting to Application Insights..." perpetually though I have another App Service's (Web App) Log streaming to the same App Insights instance working without issue.

The application starts normally when run locally out of Visual Studio 2019.

Any suggestions or input you might have to help me determine what the issue is will be greatly appreciated.

**Comment by evannielsen** [comment]
I am seeing exactly the same thing.
For added information I am only seeing this when  deployed to the East US region. I have exactly the same function code deployed to East US 2 and that function is running correctly.
Both functions are running on a Linux Consumption Plan. 

After downgrading Microsoft.NET.Sdk.Functions to 3.0.6 this issue is resolved.

@DaneVinson this might get you going for now.

**Comment by brettsam** [comment]
If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

**Comment by evannielsen** [comment]
Here is mine 2020-07-02T13:58:00.0013350+00:00', Id=b452bf92-c2f5-4c63-acc6-5ad1bd6f9baf

**Comment by brettsam** [comment]
@evannielsen -- so you're not seeing this anymore? Do you know when you moved to 3.0.6 and deployed? That'd help me look at these logs.

I do see that for a while you were getting host startup errors, but those seemed to be coming from your `FunctionStart.cs` (line 66).  The last one of those occurred at `2020-07-02 12:22:15.3810000`. Does that correspond with when you redeployed?

```
System.ArgumentNullException : Value cannot be null. (Parameter 'uriString')
```
Looking at the 3.0.7 release, there wasn't a lot that changed in the build process -- https://github.com/Azure/azure-functions-vs-build-sdk/releases/tag/3.0.7. Maybe if you could share a snippet for how you're getting the Uri for this line would help?

**Comment by evannielsen** [comment]
@brettsam I deployed with the 3.0.6 version somewhere around 7/2/2020, 8:20:18 AM Eastern. I do see that I am getting other errors getting logged in App Insights. Previous to that time the function app never made it as far as the startup function.

**Comment by DaneVinson** [comment]
@evannielsen thanks for the idea. I'll experiment with a different region.

@brettsam I cannot share the name of our Function App publicly and, as I stated originally, we cannot get any log streaming at all so I cannot get the information to share as described in your "private" link.

**Comment by brettsam** [comment]
@evannielsen: Okay, that time does line up. Your app was getting to the startup function -- but it was throwing the exception above and was failing to startup. At that point, there's no customer logging set up so we don't send the log to your App Insights, but it is visible in our backend logs. I've noted this scenario in #4705 and will push to have an improvement here.

But that still doesn't explain why 3.0.7 would have broken you -- any small repro you can share with us that shows this would be helpful. Or even a small snippet for how you're generating the uri in your startup may help.

@DaneVinson: understood. If you'd like to email me your app name directly, you can find my microsoft email in my github profile. That'd let me look in our logs for any similar startup errors.

**Comment by evannielsen** [comment]
@brettsam I see, I did make some change to the DevOps release that could have caused that error and also coincided with the downgrade to 3.0.6. The interesting part is that I was getting the "There are some issues with you runtime version." error message in the portal when I clicked the Refresh button in the function app.

**Comment by DaneVinson** [comment]
I went into the "Classic Experience" and discovered and error I hadn't seen, i.e. 
```
The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/appsettings.json'."
```
I'm not sure why it was not included, the .csproj file is set to copy newer to output but it was apparently not being deployed. I changed the file to be of type "Content" and re-deployed. Still no luck. I finally marked it as optional at load (we use the App Service configurations for our settings) and that finally seemed to work.

I only found this error in the Classic Experience blade. I don't see anywhere else that you can actually run a specific function as you can in that old blade.

**Comment by evannielsen** [comment]
@DaneVinson the appsettings problem has roots in the fact that is does not know where that file actually is on the filesystem. I ran into this a while ago and switched to using environment variables instead.

**Comment by DaneVinson** [comment]
@evannielsen Thanks for the info. I'm assuming this is an issue with Linux? We have a different Azure Function App which runs under Windows that's never had this issue. I spent quite a bit of time comparing the two applications and couldn't find significant differences. I ended up concluding it was likely something related to the difference in OS but I had no hard evidence of that.
