### ISSUE TITLE
 Exception while trying to authenticate with DefaultAzureCredential to application insights

### ISSUE THREAD

**Issue by ajarvinen** [Azure/azure-functions-host#8861]
Using DefaultAzureCredential to authenticate to Application Insights throws Exception:

`
System.Private.CoreLib: Exception while executing function: Function1. Microsoft.ApplicationInsights: The provided tokenCredential must inherit Azure.Core.TokenCredential (Parameter 'tokenCredential').
`
Here is a snippet of the code used:
```
            var config = new TelemetryConfiguration
            {
                ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://xxxxx.applicationinsights.azure.com/"
            };
            var credential = new DefaultAzureCredential();
            
            config.SetAzureTokenCredential(credential);
```
#### Expected behavior

Authentication should work to application insights using Azure AD

#### Actual behavior
Exception is thrown:
`System.Private.CoreLib: Exception while executing function: Function1. Microsoft.ApplicationInsights: The provided tokenCredential must inherit Azure.Core.TokenCredential (Parameter 'tokenCredential').`
#### Related information 

* Programming language C#
[Azure AD authentication for Application Insights](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net)

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.7.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.14.1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by jamesyao-msft** [comment]
I met the same issue

**Comment by ramya894** [comment]
@ajarvinen We are investigating the issue and update you the findings soon. Thanks

**Comment by jamesyao-msft** [comment]
@ramya894 I did some further test and found seems this issue only happens on my local run (VS2022), when I deployed this change to Azure, it's gone.

**Comment by ramya894** [comment]
closing as resolved

**Comment by jamesyao-msft** [comment]
@ramya894 We still have issue on local env while we use DefaultAzureCredential or VisualStudioCredential for TelemetryConfiguration. Looks like the issue was in code:
![image](https://user-images.githubusercontent.com/93960579/199461525-ed06a37b-755e-4af0-9e72-0df744871d59.png)


It really blocks me to use AAD for Application Insights. We cannot rollout this change while we cannot run it locally.

**Comment by mattwise-42** [comment]
@ramya894 in our tests it did not work once deployed either. We still face this issue. Can we please re-open?
<img width="686" alt="image" src="https://user-images.githubusercontent.com/106715847/202505452-f4df027d-7abf-4d96-808d-c6281d0e7a1f.png">
