### ISSUE TITLE
Timer trigger functions not invoking after migrating to .NET 8 isolated for Linux Consumption plans

### ISSUE THREAD

**Issue by sanjaybhagia** [Azure/azure-functions-host#9750]
Azure functions are running on a Linux Consumption plan with .NET 6 Isolated and working fine. In the function app, there is a timer trigger function that executes every hour, and it contains other functions, which are Service Bus and Event Hub Trigger-based. 

I have migrated the function to .Net 8 Isolated now. After the deployment, the function doesn't work. The timer trigger function is not invoked. If I manually browse the function from Azure Portal, it comes back, works for some time, and eventually dies down. 

Points to highlight: 
- The issue is not with the cron expression since .Net 6 works fine, and there hasn't been any change in the code or expression. - The expression is set in the app settings as recommended
- The function app has a dedicated blog storage account.
- I have another premium Windows plan where I have done the same, but that function works fine so far without any issues. I only have APIs in that function, though. 
- This behaviour is reproducible on other functions apps I have tried in my environment. All running on Linux Consumption plan. 
- Navigating 'Diagnose and solve problems -> Availability and performance -> Functions that are not triggering' points to the issue with the message: 

**The function app does not contain any active trigger warnings detected during this period.**(see image attached)
![image](https://github.com/Azure/azure-functions-host/assets/4527128/8701786a-2011-4109-84ba-a4d9f9224dea)

#### Investigative information

Please provide the following:

- Timestamp: 2023-12-27T02:51:17Z
- Function App version: v4
- Function App name: DataTrigger
- Function name(s) (as appropriate):
- Invocation ID: bebb9f3f-6d70-44ed-9e6d-5d96d7a3ae35
- Region: Australia East

#### Expected behavior

The timer trigger function should invoke every hour based on the set schedule (cron). 

![image](https://github.com/Azure/azure-functions-host/assets/4527128/164bb142-deaf-40c2-868a-98f4e5636527)#### Actual behavior

Provide a description of the actual behavior observed.

![image](https://github.com/Azure/azure-functions-host/assets/4527128/bc639896-db01-4ecd-a9ec-b2168be74f4e)

#### Known workarounds

Navigating the function from Azure Portal triggers the functions for some time. 

#### Related information 

Provide any related information 
- .NET 8
- Cron expression: 0 0 * * * *
- .csproj file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Functions\Shared.Functions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

- Other nuget packages references from shared project
```xml
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="7.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.0.3" />
    <PackageReference Include="Microsoft.Azure.Management.EventHub" Version="5.0.0" />	  
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.38.1" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.2" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.11" />
    <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.11" />
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.42.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.0.3" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.15.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.SignalRService" Version="1.12.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />

     <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.17.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.10" />
    <PackageReference Include="Tinify" Version="1.6.0" />

    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.2.0" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="CsvHelper" Version="30.0.1" />

    <PackageReference Include="GeoTimeZone" Version="5.3.0" />
    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
    <PackageReference Include="DocumentFormat.OpenXml.Features" Version="3.0.0" />
	  
   <PackageReference Include="HttpMultipartParser" Version="8.2.0" />

  <PackageReference Include="Azure.Data.Tables" Version="12.8.2" />
  <PackageReference Include="Azure.DigitalTwins.Core" Version="1.4.0" />    
  <PackageReference Include="Azure.Messaging.EventHubs" Version="5.10.0" />
  <PackageReference Include="GeoJSON.Net" Version="1.2.19" />
  <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.37.0" />
  <PackageReference Include="Microsoft.Graph" Version="5.37.0" />

  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
```

**Comment by kshyju** [comment]
@sanjaybhagia 

1. Does your timer trigger work when running/debugging locally?
2. Where are you defining your cron expression for the timer trigger? 
3. Can you share your timer trigger method signature?

**Comment by sanjaybhagia** [comment]
1. Does your timer trigger work when running/debugging locally?
     Yes, works fine locally and running on .net 6 isolated
2. Where are you defining your cron expression for the timer trigger?
     App Settings (expression: 0 0 * * * *)
3. Can you share your timer trigger method signature?
     `[Function(nameof(DataTrigger))]
        public async Task Run([TimerTrigger("%data_trigger_timer%", RunOnStartup = false)] TimerInfo myTimer)
        {
            // removed
        }`

**Comment by kshyju** [comment]
@sanjaybhagia Does restarting your app work? If not, I recommend opening a support ticket for deeper investigation of your app.

**Comment by sanjaybhagia** [comment]
No, restarting doesn't help with this.

**Comment by kshyju** [comment]
Please open a support ticket so that the team can take a deeper look at your application. Thanks!

**Comment by silvacaio** [comment]
Any update about that issue @kshyju ? We are facing the same problem with a function that have a Service Bus trigger.

**Comment by Morras** [comment]
I might have a solution to this problem.

My function would start correctly when deployed and fire any triggers that was overdue, but according to the logs, after 20 minutes the Job host would be stopped and never start up again.

If I restarted the function app the Job host would start and run any past due triggers, but again it would stop after 20 minutes.

After struggling through MS support (TrackingID#2312140050000795 if anyone from MS is interested) since mid december with this, I finally caught a break last week.

I used **Microsoft.Azure.Functions.Worker.Sdk version 1.16.3** but if I downgraded that to **Microsoft.Azure.Functions.Worker.Sdk version 1.15.1** then it worked.

This was on .NET 7, in an isolated Windows consumption plan, so a slightly different setup than the original post, however the SDK version numbers are similar.

**Comment by sanjaybhagia** [comment]
This is parsing related issue (https://github.com/Azure/azure-functions-dotnet-worker/pull/2234) and has been resolved. Please use Microsoft.Azure.Functions.Worker.Sdk 1.17.0-preview1 or higher.

**Comment by kolexinfos** [comment]
I am running into the same issue where Timer-Triggered functions are not **firing** in **.Net 8 and Isolated mode** and I have updated all my packages as shown below but still the triggers does not fire when deployed in Azure using **az deploy** with zip. 

I am wondering if there is a mismatch in Function Core tools(func), what is the version of the Azure Runtime that your Function App is using in Azure.

The triggers fire locally and my func version locally is 4.0.5455.

```
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.13.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.1.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Warmup" Version="4.0.2" />
```

**Comment by danelec-hpm** [comment]
Make sure you have a local.settings.json file in the root of your function project. The content should look like this:
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}

Adding this file worked for me. Apparently this file was not needed in previous dotnet versions to run locally or some developer forgot to commit it to the repository.

**Comment by Angelm116** [comment]
Hello @sanjaybhagia, 

I am using Microsoft.Azure.Functions.Worker.Sdk 1.17.4 and am still having this issue. Any recommendations?

**Comment by BabzDev** [comment]
> Hello [@sanjaybhagia](https://github.com/sanjaybhagia),
> 
> I am using Microsoft.Azure.Functions.Worker.Sdk 1.17.4 and am still having this issue. Any recommendations?

Likewise, we are using the latest version of worker sdk and still seeing the same problem. We have a blob storage triggered function, which is doing some simple processing. On occasion when things don't happen the way expected, we throw an exception. 

I see exactly the same pattern as in the graphs above, the function works for say 20 minutes, and then it stops processing for another 15-20 minutes.

**Comment by UsherNet** [comment]
Odd that this issue is closed, but no clear fix.

I just migrated to an isolated timer based function with Microsoft.Azure.Functions.Worker 2.0.0, Microsoft.Azure.Functions.Worker.Extensions.Timer 4.3.1 and Microsoft.Azure.Functions.Worker.Sdk 2.0.4 running on a Linux consumption plan and the function does not run more than once.  It is set to run once per day.  Older version (in-process) worked flawlessly 

Any thoughts?

**Comment by kshyju** [comment]
@UsherNet The most effective way to ensure this gets investigated and resolved is by opening a support ticket. This enables the team to conduct a deeper analysis of your app.
